audiad/music/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
import audiad.music.views.genre
from audiad.music.views.album import *
from audiad.music.views.song import *
from audiad.music.views.artist import *
from audiad.music.views.label import *
from audiad.music.views.genre import *
from audiad.music.views.views import IndexView
from audiad.music.views import views, song, album, artist, label, genre

app_name = 'music'

# todo Sort URL's to avoid unreachable links

urlpatterns = [

    # BASE PAGES ##
    # /music/
    url(r'^$', IndexView.as_view(), name='index'),

    # ALBUMS ##
    # /music/view/albums/<all:favourites>
    url(r'^view/albums/(?P<filter_by>[a-zA_Z]+)/$', Albums.as_view(), name='albums'),
    # /music/view/album/<album_id>
    url(r'^view/album/(?P<pk>\d+)/$', AlbumView.as_view(), name='album_form'),
    # /music/list/albums/<all:favourites>
    url(r'^list/albums/$', AlbumList.as_view(), name='albums_list'),
    # /music/table/albums/<all:favourites>
    url(r'^table/albums/$', AlbumTable.as_view(), name='albums_table'),
    # /music/detail/albums/<album_id>
    url(r'^detail/album/(?P<pk>\d+)$', AlbumDetailView.as_view(), name='album_detail'),
    # /music/edit/albums/<album_id>/
    url(r'^edit/album/(?P<pk>\d+)$', AlbumUpdate.as_view(), name='edit_album'),
    # /music/delete/albums/<album_id>
    url(r'^delete/album/(?P<pk>\d+)$', AlbumDelete.as_view(), name='delete_album'),
    # /music/create/album
    url(r'^create/album/$', AlbumCreate.as_view(), name='create_album'),
    # /music/favorite_album/<album_id>
    url(r'^favorite_album/(?P<album_id>[0-9]+)$', album.fav_album, name='fav_album'),
    # /music/filter/albums/
    url(r'^filter/albums$', views.filter_album, name='filter_album'),

    # SONGS ##
    # /music/songs/<all:favourites>
    url(r'^view/songs/(?P<filter_by>[a-zA_Z]+)/$', Songs.as_view(), name='songs'),
    # /music/list/song/
    url(r'^list/song/$', SongList.as_view(), name='song_list'),
    # /music/table/song/
    url(r'^table/song/$', SongTable.as_view(), name='song_table'),
    # /music/songs/<song_id>
    url(r'^detail/song/(?P<pk>\d+)$', SongDetailView.as_view(), name='song_detail'),
    # /music/songs/<song_id>/view
    url(r'^view/song/(?P<pk>\d+)/$', SongView.as_view(), name='song_form'),
    # /music/songs/<song_id>/edit/
    url(r'^edit/song/(?P<pk>\d+)$', SongUpdate.as_view(), name='edit_song'),
    # /music/songs/<song_id>/delete
    url(r'^delete/song/(?P<pk>\d+)$', SongDelete.as_view(), name='delete_song'),
    # /music/create/songs
    url(r'^create/song/$', SongCreate.as_view(), name='create_song'),
    # /music/<song_id>/favorite_song
    url(r'^(?P<song_id>[0-9]+)/favorite_song/$', song.fav_song, name='fav_song'),
    # /music/filter/songs/
    url(r'^filter/songs', views.filter_song, name='filter_songs'),

    # ARTISTS ##
    # /music/artist/<all:favourites>
    url(r'^view/artists/(?P<filter_by>[a-zA_Z]+)/$', Artists.as_view(), name='artists'),
    # /music/list/artist/
    url(r'^list/artists/$', ArtistList.as_view(), name='artists_list'),
    # /music/table/artist/
    url(r'^table/artists/$', ArtistTable.as_view(), name='artists_table'),
    # /music/artist/<artist_id>
    url(r'^detail/artist/(?P<pk>\d+)$', ArtistDetailView.as_view(), name='artist_detail'),
    # /music/artist/<artist_id>/view
    url(r'^view/artist/(?P<pk>\d+)/$', ArtistView.as_view(), name='artist_form'),
    # /music/artist/<artist_id>/edit/
    url(r'^edit/artist/(?P<pk>\d+)$', ArtistUpdate.as_view(), name='edit_artist'),
    # /music/artist/<artist_id>/delete
    url(r'^delete/artist/(?P<pk>\d+)$', ArtistDelete.as_view(), name='delete_artist'),
    # /music/create/artist
    url(r'^create/artist/$', ArtistCreate.as_view(), name='create_artist'),
    # /music/<artist_id>/favorite_artist
    url(r'^(?P<artist_id>[0-9]+)/favorite_artist/$', artist.fav_artist, name='fav_artist'),
    # /music/filter/artists/
    url(r'^filter/artists', views.filter_artist, name='filter_artist'),
    
    # GENRE ##
    # /music/genre/<all:favourites>
    url(r'^view/genres/(?P<filter_by>[a-zA_Z]+)/$', Genres.as_view(), name='genres'),
    # /music/list/genre/<all:favourites>
    url(r'^list/genres/$', GenreList.as_view(), name='genre_list'),
    # /music/table/genre/<all:favourites>
    url(r'^table/genres/$', GenreTable.as_view(), name='genre_table'),
    # /music/genre/<genre_id>
    url(r'^detail/genre/(?P<pk>\d+)$', GenreDetailView.as_view(), name='genre_detail'),
    # /music/genre/<genre_id>/view
    url(r'^view/genre/(?P<pk>\d+)/$', GenreView.as_view(), name='genre_form'),
    # /music/genre/<genre_id>/edit/
    url(r'^edit/genre/(?P<pk>\d+)$', GenreUpdate.as_view(), name='edit_genre'),
    # /music/genre/<genre_id>/delete
    url(r'^delete/genre/(?P<pk>\d+)$', GenreDelete.as_view(), name='delete_genre'),
    # /music/create/genre
    url(r'^create/genre/$', GenreCreate.as_view(), name='create_genre'),
    # /music/<genre_id>/favorite_genre
    url(r'^(?P<genre_id>[0-9]+)/favorite_genre/$', genre.fav_genre, name='fav_genre'),
    # /music/filter/genre/
    url(r'^filter/genre', views.filter_genre, name='filter_genre'),

    # LABEL ##
    # /music/label/<all:favourites>
    url(r'^view/labels/(?P<filter_by>[a-zA_Z]+)/$', Labels.as_view(), name='labels'),
    # /music/list/label/<all:favourites>
    url(r'^list/labels/$', LabelList.as_view(), name='label_list'),
    # /music/table/label/<all:favourites>
    url(r'^table/labels/$', LabelTable.as_view(), name='label_table'),
    # /music/label/<label_id>
    url(r'^detail/label/(?P<pk>\d+)$', LabelDetailView.as_view(), name='label_detail'),
    # /music/label/<label_id>/view
    url(r'^view/label/(?P<pk>\d+)/$', LabelView.as_view(), name='label_form'),
    # /music/label/<label_id>/edit/
    url(r'^edit/label/(?P<pk>\d+)$', LabelUpdate.as_view(), name='edit_label'),
    # /music/label/<label_id>/delete
    url(r'^delete/label/(?P<pk>\d+)$', LabelDelete.as_view(), name='delete_label'),
    # /music/create/label
    url(r'^create/label/$', LabelCreate.as_view(), name='create_label'),
    # /music/<label_id>/favorite_label
    url(r'^(?P<label_id>[0-9]+)/favorite_label/$', label.fav_label, name='fav_label'),
    # /music/filter/label/
    url(r'^filter/label', views.filter_label, name='filter_label'),

    # SEARCH ##
    # /music/search_results
    url(r'^search_results/$', views.searchresults, name='searchresults'),

    # USER AND AUTH ##
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    # url(r'^profile/$', views.update_profile, name='update_profile'),

    # MEDIA ##
    # url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT, }),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

audiad/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib import admin


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='home.html')),
    url(r'^music/', include('audiad.music.urls', namespace='music')),
    url(r'^admin/', include(admin.site.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

audiad/music/views/album.py
"""docstrings.


Example:


Attributes:
    module_level_variable1 (int): Module level variables may be documented in
        either the ``Attributes`` section of the module docstring, or in an
        inline docstring immediately following the variable.

Todo:

"""
# todo Finish docstring

from digg_paginator import DiggPaginator as Paginator
from django.core.paginator import PageNotAnInteger, EmptyPage
from django.core.urlresolvers import reverse_lazy
from django.db.models import Q, F
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, FormView, DetailView, UpdateView, DeleteView, CreateView, View
from django_tables2 import RequestConfig
from django_tables2.export import TableExport
from audiad.music.forms import AlbumForm
from audiad.music.models import Album, Artist, Song
from audiad.music.tables import AlbumTable as AT
from django.conf import settings
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.shortcuts import render
from django.views.decorators.cache import cache_page

CACHE_TTL = getattr(settings, 'CACHE_TTL', DEFAULT_TIMEOUT)


class Albums(View):
    """docstring

    Properties created with the ``@property`` decorator should be documented
    in the property's getter method.

    Attributes:
        attr1 (str): Description of `attr1`.
        attr2 (:obj:`int`, optional): Description of `attr2`.

    """
    # todo Finish docstring

    def get(self, request, filter_by='all'):
        """docstring

                Note:
                    Do not include the `self` parameter in the ``Args`` section.

                Args:
                    param1: The first parameter.
                    param2: The second parameter.

                Returns:
                    True if successful, False otherwise.

                """
        # todo Finish docstring
        if not request.user.is_authenticated():
            return render(request, 'music/auth/login.html')
        else:
            page = request.GET.get('page', 1)
            try:
                album_ids = []
                user_albums = []
                for album in Album.objects.filter(user=request.user):
                    album_ids.append(album.pk)
                    user_albums = Album.objects.filter(pk__in=album_ids)
                if user_albums:
                    if filter_by == 'favorites':
                        user_albums = user_albums.filter(fav=True)
            #     paginate_albums = Paginator(user_albums, 20, body=3, margin=1, tail=1)
            #     try:
            #         user_albums = paginate_albums.page(page)
            #     except PageNotAnInteger:
            #         user_albums = paginate_albums.page(1)
            #     except EmptyPage:
            #         user_albums = paginate_albums.page(paginate_albums.num_pages)
            except Album.DoesNotExist:
                user_albums = []
            return render(request, 'music/album/albums.html', {
                'album_list': user_albums,
                'filter_by': filter_by,
            })


class AlbumTable(ListView):
    """docstring

    Properties created with the ``@property`` decorator should be documented
    in the property's getter method.

    Attributes:
        attr1 (str): Description of `attr1`.
        attr2 (:obj:`int`, optional): Description of `attr2`.

    """
    # todo Finish docstring

    template_name = 'music/album/album_table.html'
    model = Album

    def get_context_data(self, **kwargs):
        """docstring

                Note:
                    Do not include the `self` parameter in the ``Args`` section.

                Args:
                    param1: The first parameter.
                    param2: The second parameter.

                Returns:
                    True if successful, False otherwise.

                """
        # todo Finish docstring
        if not self.request.user.is_authenticated():
            return render(self.request, 'music/auth/login.html')
        else:
            user = self.request.user
            context = super(AlbumTable, self).get_context_data(**kwargs)
            table = AT(Album.objects.all())
            table.paginate(page=self.request.GET.get('page', 1), per_page=25)
            RequestConfig(self.request).configure(table)
            export_format = self.request.GET.get('_export', None)
            if TableExport.is_valid_format(export_format):
                exporter = TableExport(export_format, table)
                return exporter.response('table.{}'.format(export_format))
            context['user'] = user
            context['table'] = table
            return context


class AlbumList(ListView):
    """docstring

    Properties created with the ``@property`` decorator should be documented
    in the property's getter method.

    Attributes:
        attr1 (str): Description of `attr1`.
        attr2 (:obj:`int`, optional): Description of `attr2`.

    """
    # todo Finish docstring

    def get(self, request, filter_by='all'):
        """docstring

                Note:
                    Do not include the `self` parameter in the ``Args`` section.

                Args:
                    param1: The first parameter.
                    param2: The second parameter.

                Returns:
                    True if successful, False otherwise.

                """
        # todo Finish docstring
        if not request.user.is_authenticated():
            return render(request, 'music/auth/login.html')
        else:
            page = request.GET.get('page', 1)
            try:
                album_ids = []
                albums = []
                for album in Album.objects.all():
                    album_ids.append(album.pk)
                    albums = Album.objects.filter(pk__in=album_ids)
                if filter_by == 'favorites':
                    albums = albums.filter(fav=True)
                paginate_albums = Paginator(albums, 20, body=3, margin=1, tail=1)
                try:
                    albums = paginate_albums.page(page)
                except PageNotAnInteger:
                    albums = paginate_albums.page(1)
                except EmptyPage:
                    albums = paginate_albums.page(paginate_albums.num_pages)
            except Album.DoesNotExist:
                albums = []
            return render(request, 'music/album/album_list.html', {
                'album_list': albums,
                'filter_by': filter_by,
            })


class AlbumDetailView(DetailView):
    """docstring

    Properties created with the ``@property`` decorator should be documented
    in the property's getter method.

    Attributes:
        attr1 (str): Description of `attr1`.
        attr2 (:obj:`int`, optional): Description of `attr2`.

    """
    # todo Finish docstring

    template_name = 'music/album/album_detail.html'
    model = Album

    def get_context_data(self, **kwargs):
        """docstring

                Note:
                    Do not include the `self` parameter in the ``Args`` section.

                Args:
                    param1: The first parameter.
                    param2: The second parameter.

                Returns:
                    True if successful, False otherwise.

                """
        # todo Finish docstring
        if not self.request.user.is_authenticated():
            return render(self.request, 'music/auth/login.html')
        else:
            user = self.request.user
            albums = Album.objects.all()
            artists = Artist.objects.all()
            songs = Song.objects.all()
            album = self.object
            context = super(AlbumDetailView, self).get_context_data(**kwargs)
            context['album'] = album
            context['user'] = user
            if self.object.genre.name:
                genre = self.object.genre.name
            context['similar_artist'] = artists.filter(Q(genre__name__icontains=genre)).distinct().exclude(name=album.artist)[:5]
            context['similar_album'] = albums.filter(Q(genre__name__icontains=genre)).distinct().exclude(title=album.title).filter(artist=F('artist')).distinct()[:5]
            context['similar_song'] = songs.filter(Q(genre__name__icontains=genre)).distinct().exclude(album=album.id)[:5]
            return context


class AlbumUpdate(UpdateView):
    """docstring

    Properties created with the ``@property`` decorator should be documented
    in the property's getter method.

    Attributes:
        attr1 (str): Description of `attr1`.
        attr2 (:obj:`int`, optional): Description of `attr2`.

    """
    # todo Finish docstring

    # todo Doesnt populate fields
    model = Album
    form_class = AlbumForm
    template_name = 'music/album/album_update.html'
    success_url = reverse_lazy('music:albums' 'all')

    def get_initial(self):
        initial = super(AlbumUpdate, self).get_initial()
        return initial


class AlbumView(FormView):
    """docstring

    Properties created with the ``@property`` decorator should be documented
    in the property's getter method.

    Attributes:
        attr1 (str): Description of `attr1`.
        attr2 (:obj:`int`, optional): Description of `attr2`.

    """
    # todo Finish docstring

    template_name = 'music/album/album_create.html'
    form_class = AlbumForm
    success_url = '/index/'

    # def form_valid(self, form):
    #     """docstring
    #
    #             Note:
    #                 Do not include the `self` parameter in the ``Args`` section.
    #
    #             Args:
    #                 param1: The first parameter.
    #                 param2: The second parameter.
    #
    #             Returns:
    #                 True if successful, False otherwise.
    #
    #             """
    #     # todo Finish docstring
    #     if not self.request.user.is_authenticated():

audiad/music/templates/music/home.html
{% extends "base.html" %}

{% block heading %}Home{% endblock %}

{% block content %}

{% endblock content %}

audiad/music/templates/music/index.html
{% extends 'base.html' %}
{% block title %}Welcome to Audiad{% endblock %}
{% block index_active %}active{% endblock %}
{% block body %}

    <!-- Dynamic Content -->
    <div class="albums-container container-fluid">

        <!-- Main Body -->
        <div class="row">
            <div class="col-sm-12 title">
                <h1>Music Manager</h1>
                <h2>Welcome {{ user.username.title }}</h2>
                <h5>You have {{ albums_count }} Albums</h5>
                <h5>You have {{ songs_count }} Songs</h5>
                <h5>You have {{ artists_count }} Artists</h5>
{#                <ul>#}
{#                    {% for url, text in urls %}#}
{#                        <li><a href="{{ url }}">{{ text }}</a></li>#}
{#                    {% endfor %}#}
{#                </ul>#}
                <h4>Nav</h4>
                <li><a href="{% url 'music:index' %}">Here</a></li>
                <li><a href="{% url 'music:register'%}">register</a></li>
                <li><a href="{% url 'music:login_user'%}">login_user</a></li>
                <li><a href="{% url 'music:logout_user'%}">logout_user</a></li>

                <h4>Artists</h4>
                <li><a href="{% url 'music:artists' 'all' %}">artists All</a></li>
                <li><a href="{% url 'music:artists' 'favorites' %}">artists Fav</a></li>
                <li><a href="{% url 'music:artists_list' %}">artists list</a></li>
                <li><a href="{% url 'music:artists_table' %}">artists table</a></li>
                <li><a href="{% url 'music:create_artist'%}">create artist</a></li>

                <h4>Albums</h4>
                <li><a href="{% url 'music:albums' 'all' %}">albums All</a></li>
                <li><a href="{% url 'music:albums' 'favorites' %}">albums Fav</a></li>
                <li><a href="{% url 'music:albums_list' %}">albums list</a></li>
                <li><a href="{% url 'music:albums_table' %}">albums table</a></li>
                <li><a href="{% url 'music:create_album'%}">create album</a></li>

                <h4>Songs</h4>
                <li><a href="{% url 'music:songs' 'all' %}">songs All</a></li>
                <li><a href="{% url 'music:songs' 'favorites' %}">songs Fav</a></li>
                <li><a href="{% url 'music:song_list' %}">songs list</a></li>
                <li><a href="{% url 'music:song_table' %}">songs table</a></li>
                <li><a href="{% url 'music:create_song'%}">create song</a></li>

                <h4>Genre</h4>
                <li><a href="{% url 'music:genres' 'all' %}">genre All</a></li>
                <li><a href="{% url 'music:genres' 'favorites' %}">genre Fav</a></li>
                <li><a href="{% url 'music:genre_list' %}">genre list</a></li>
                <li><a href="{% url 'music:genre_table' %}">genre table</a></li>
                <li><a href="{% url 'music:create_genre'%}">create genre</a></li>

                <h4>Label</h4>
                <li><a href="{% url 'music:labels' 'all' %}">label All</a></li>
                <li><a href="{% url 'music:labels' 'favorites' %}">label Fav</a></li>
                <li><a href="{% url 'music:label_list' %}">label list</a></li>
                <li><a href="{% url 'music:label_table' %}">label table</a></li>
                <li><a href="{% url 'music:create_label'%}">create label</a></li>

                <h4>Search</h4>
                <li><a href="{% url 'music:filter_songs'%}">song search</a></li>
                <li><a href="{% url 'music:filter_album'%}">album search</a></li>
                <li><a href="{% url 'music:filter_artist'%}">artist search</a></li>
                <li><a href="{% url 'music:filter_genre'%}">genre search</a></li>
                <li><a href="{% url 'music:filter_label'%}">label search</a></li>
                <li><a href="{% url 'music:searchresults'%}">searchresults</a></li>
                {#<li><a href="{% url 'music:search'%}">search</a></li>#}

            </div>
        </div>

        <!-- Fav Albums Panel -->
        <div class="row">
        <h2>Favourite Albums</h2>
            {% if user_albums %}

                <!-- Iterate Through Albums-->
                {% for album in user_albums %}

                    <!-- Panel -->
                    <div class="col-sm-4 col-lg-2">
                        <div class="thumbnail">

                            <!-- Album Image to go here -->
                            <a href="{% url 'music:album_detail' album.id %}"></a>

                            <!-- Main Caption -->
                            <div class="caption">

                                <!-- Albums Details -->
                                <h2>{{ album.title }}</h2>
                                <h4>{{ album.artist }}</h4>

                                <!-- View Details -->
                                <a href="{% url 'music:album_detail' album.id %}" class="btn btn-primary btn-sm"
                                   role="button">View
                                    Details</a>

                                <!-- Delete Album -->
                                <!-- Get POST -->
                                <form action="{% url 'music:delete_album' album.id %}" method="post"
                                      style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="album_id" value="{{ album.id }}"/>
                                    <button type="submit" class="btn btn-default btn-sm">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </button>
                                </form>

                                <!-- Edit -->
                                <!-- Uses GET -->
                                <form action="{% url 'music:edit_album' album.id %}" method="get"
                                      style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="album_id" value="{{ album.id }}"/>
                                    <button type="submit" class="btn btn-default btn-sm"/>
                                    <span class="glyphicon glyphicon-edit"></span>
                                    </button>
                                </form>

                                <!-- Favorite Album -->
                                <a href="{% url 'music:fav_album' album.id %}"
                                   class="btn btn-default btn-sm btn-favorite"
                                   role="button">
                                    <span class="glyphicon glyphicon-star {% if album.fav %}active{% endif %}"></span>
                                </a>

                            </div>

                        </div>
                    </div>

                    <!-- ?? -->
                    {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}

                {% endfor %}

            {% else %}
                <p>There are no albums to show</p>

            {% endif %}
        </div>

        <!-- Fav Artists Panel -->
        <div class="row">
        <h2>Favourite Artists</h2>
            {% if user_artists%}

                <!-- Iterate Through Artist-->
                {% for artist in user_artists %}

                    <!-- Panel -->
                    <div class="col-sm-4 col-lg-2">
                        <div class="thumbnail">

                            <!-- Artist Image to go here -->
                            <a href="{% url 'music:artist_detail' artist.id %}"></a>

                            <!-- Main Caption -->
                            <div class="caption">

                                <!-- Artist Details -->
                                <h2>{{ artist.name }}</h2>
                                <h4>{{ artist.genre.all }}</h4>

                                <!-- View Details -->
                                <a href="{% url 'music:artist_detail' artist.id %}" class="btn btn-primary btn-sm"
                                   role="button">View
                                    Details</a>

                                <!-- Delete Artist -->
                                <!-- Uses POST -->
                                <form action="{% url 'music:delete_artist' artist.id %}" method="post"
                                      style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="artist_id" value="{{ artist.id }}"/>
                                    <button type="submit" class="btn btn-default btn-sm">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </button>
                                </form>

                                <!-- Edit Artist -->
                                <!-- Uses GET -->
                                <form action="{% url 'music:edit_artist' artist.id %}" method="get"
                                      style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="artist_id" value="{{ artist.id }}"/>
                                    <button type="submit" class="btn btn-default btn-sm"/>
                                    <span class="glyphicon glyphicon-edit"></span>
                                    </button>
                                </form>

                                <!-- Favorite Artist -->
                                <a href="{% url 'music:fav_artist' artist.id %}"
                                   class="btn btn-default btn-sm btn-favorite"
                                   role="button">
                                    <span class="glyphicon glyphicon-star {% if artist.fav %}active{% endif %}"></span>
                                </a>

                            </div>

                        </div>
                    </div>

                    <!-- ?? -->
                    {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}

                {% endfor %}

            {% else %}
                <p>There are no albums to show</p>

            {% endif %}
        </div>

        <!-- Fav Songs Panel -->
        <div class="row">
        <h2>Favourite Songs</h2>
            {% if user_songs %}

                <!-- Iterate Through Albums-->
                {% for song in user_songs %}

                    <!-- Panel -->
                    <div class="col-sm-4 col-lg-2">
                        <div class="thumbnail">

                            <!-- Songs Image to go here -->
                            <a href="{% url 'music:song_detail' song.id %}"></a>

                            <!-- Main Caption -->
                            <div class="caption">

                                <!-- Songs Details -->
                                <h2>{{ song.title }}</h2>
                                <h4>{{ song.artist }}</h4>

                                <!-- View Details -->
                                <a href="{% url 'music:song_detail' song.id %}" class="btn btn-primary btn-sm"
                                   role="button">View
                                    Details</a>

                                <!-- Delete Songs -->
                                <!-- Uses POST -->
                                <form action="{% url 'music:delete_song' song.id %}" method="post"
                                      style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="song_id" value="{{ song.id }}"/>
                                    <button type="submit" class="btn btn-default btn-sm">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </button>
                                </form>

                                <!-- Edit -->
                                <!-- Uses GET -->
                                <form action="{% url 'music:edit_song' song.id %}" method="get"
                                      style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="song_id" value="{{ song.id }}"/>
                                    <button type="submit" class="btn btn-default btn-sm"/>
                                    <span class="glyphicon glyphicon-edit"></span>
                                    </button>
                                </form>

                                <!-- Favorite Songs -->
                                <a href="{% url 'music:fav_song' song.id %}"
                                   class="btn btn-default btn-sm btn-favorite"
                                   role="button">
                                    <span class="glyphicon glyphicon-star {% if song.fav %}active{% endif %}"></span>
                                </a>

                            </div>

                        </div>
                    </div>

                    <!-- ?? -->
                    {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}

                {% endfor %}

            {% else %}
                <p>There are no albums to show</p>

            {% endif %}
        </div>


    </div>

{% endblock %}