audiad/music/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
import audiad.music.views.genre
from audiad.music.views.album import *
from audiad.music.views.song import *
from audiad.music.views.artist import *
from audiad.music.views.label import *
from audiad.music.views.genre import *
from audiad.music.views.views import IndexView
from audiad.music.views import views, song, album, artist, label, genre

app_name = 'music'

# todo Sort URL's to avoid unreachable links

urlpatterns = [

    # BASE PAGES ##
    # /music/
    url(r'^$', IndexView.as_view(), name='index'),

    # ALBUMS ##
    # /music/view/albums/<all:favourites>
    url(r'^view/albums/(?P<filter_by>[a-zA_Z]+)/$', Albums.as_view(), name='albums'),
    # /music/view/album/<album_id>
    url(r'^view/album/(?P<pk>\d+)/$', AlbumView.as_view(), name='album_form'),
    # /music/list/albums/<all:favourites>
    url(r'^list/albums/$', AlbumList.as_view(), name='albums_list'),
    # /music/table/albums/<all:favourites>
    url(r'^table/albums/$', AlbumTable.as_view(), name='albums_table'),
    # /music/detail/albums/<album_id>
    url(r'^detail/album/(?P<pk>\d+)$', AlbumDetailView.as_view(), name='album_detail'),
    # /music/edit/albums/<album_id>/
    url(r'^edit/album/(?P<pk>\d+)$', AlbumUpdate.as_view(), name='edit_album'),
    # /music/delete/albums/<album_id>
    url(r'^delete/album/(?P<pk>\d+)$', AlbumDelete.as_view(), name='delete_album'),
    # /music/create/album
    url(r'^create/album/$', AlbumCreate.as_view(), name='create_album'),
    # /music/favorite_album/<album_id>
    url(r'^favorite_album/(?P<album_id>[0-9]+)$', album.fav_album, name='fav_album'),
    # /music/filter/albums/
    url(r'^filter/albums$', views.filter_album, name='filter_album'),

    # SONGS ##
    # /music/songs/<all:favourites>
    url(r'^view/songs/(?P<filter_by>[a-zA_Z]+)/$', Songs.as_view(), name='songs'),
    # /music/list/song/
    url(r'^list/song/$', SongList.as_view(), name='song_list'),
    # /music/table/song/
    url(r'^table/song/$', SongTable.as_view(), name='song_table'),
    # /music/songs/<song_id>
    url(r'^detail/song/(?P<pk>\d+)$', SongDetailView.as_view(), name='song_detail'),
    # /music/songs/<song_id>/view
    url(r'^view/song/(?P<pk>\d+)/$', SongView.as_view(), name='song_form'),
    # /music/songs/<song_id>/edit/
    url(r'^edit/song/(?P<pk>\d+)$', SongUpdate.as_view(), name='edit_song'),
    # /music/songs/<song_id>/delete
    url(r'^delete/song/(?P<pk>\d+)$', SongDelete.as_view(), name='delete_song'),
    # /music/create/songs
    url(r'^create/song/$', SongCreate.as_view(), name='create_song'),
    # /music/<song_id>/favorite_song
    url(r'^(?P<song_id>[0-9]+)/favorite_song/$', song.fav_song, name='fav_song'),
    # /music/filter/songs/
    url(r'^filter/songs', views.filter_song, name='filter_songs'),

    # ARTISTS ##
    # /music/artist/<all:favourites>
    url(r'^view/artists/(?P<filter_by>[a-zA_Z]+)/$', Artists.as_view(), name='artists'),
    # /music/list/artist/
    url(r'^list/artists/$', ArtistList.as_view(), name='artists_list'),
    # /music/table/artist/
    url(r'^table/artists/$', ArtistTable.as_view(), name='artists_table'),
    # /music/artist/<artist_id>
    url(r'^detail/artist/(?P<pk>\d+)$', ArtistDetailView.as_view(), name='artist_detail'),
    # /music/artist/<artist_id>/view
    url(r'^view/artist/(?P<pk>\d+)/$', ArtistView.as_view(), name='artist_form'),
    # /music/artist/<artist_id>/edit/
    url(r'^edit/artist/(?P<pk>\d+)$', ArtistUpdate.as_view(), name='edit_artist'),
    # /music/artist/<artist_id>/delete
    url(r'^delete/artist/(?P<pk>\d+)$', ArtistDelete.as_view(), name='delete_artist'),
    # /music/create/artist
    url(r'^create/artist/$', ArtistCreate.as_view(), name='create_artist'),
    # /music/<artist_id>/favorite_artist
    url(r'^(?P<artist_id>[0-9]+)/favorite_artist/$', artist.fav_artist, name='fav_artist'),
    # /music/filter/artists/
    url(r'^filter/artists', views.filter_artist, name='filter_artist'),
    
    # GENRE ##
    # /music/genre/<all:favourites>
    url(r'^view/genres/(?P<filter_by>[a-zA_Z]+)/$', Genres.as_view(), name='genres'),
    # /music/list/genre/<all:favourites>
    url(r'^list/genres/$', GenreList.as_view(), name='genre_list'),
    # /music/table/genre/<all:favourites>
    url(r'^table/genres/$', GenreTable.as_view(), name='genre_table'),
    # /music/genre/<genre_id>
    url(r'^detail/genre/(?P<pk>\d+)$', GenreDetailView.as_view(), name='genre_detail'),
    # /music/genre/<genre_id>/view
    url(r'^view/genre/(?P<pk>\d+)/$', GenreView.as_view(), name='genre_form'),
    # /music/genre/<genre_id>/edit/
    url(r'^edit/genre/(?P<pk>\d+)$', GenreUpdate.as_view(), name='edit_genre'),
    # /music/genre/<genre_id>/delete
    url(r'^delete/genre/(?P<pk>\d+)$', GenreDelete.as_view(), name='delete_genre'),
    # /music/create/genre
    url(r'^create/genre/$', GenreCreate.as_view(), name='create_genre'),
    # /music/<genre_id>/favorite_genre
    url(r'^(?P<genre_id>[0-9]+)/favorite_genre/$', genre.fav_genre, name='fav_genre'),
    # /music/filter/genre/
    url(r'^filter/genre', views.filter_genre, name='filter_genre'),

    # LABEL ##
    # /music/label/<all:favourites>
    url(r'^view/labels/(?P<filter_by>[a-zA_Z]+)/$', Labels.as_view(), name='labels'),
    # /music/list/label/<all:favourites>
    url(r'^list/labels/$', LabelList.as_view(), name='label_list'),
    # /music/table/label/<all:favourites>
    url(r'^table/labels/$', LabelTable.as_view(), name='label_table'),
    # /music/label/<label_id>
    url(r'^detail/label/(?P<pk>\d+)$', LabelDetailView.as_view(), name='label_detail'),
    # /music/label/<label_id>/view
    url(r'^view/label/(?P<pk>\d+)/$', LabelView.as_view(), name='label_form'),
    # /music/label/<label_id>/edit/
    url(r'^edit/label/(?P<pk>\d+)$', LabelUpdate.as_view(), name='edit_label'),
    # /music/label/<label_id>/delete
    url(r'^delete/label/(?P<pk>\d+)$', LabelDelete.as_view(), name='delete_label'),
    # /music/create/label
    url(r'^create/label/$', LabelCreate.as_view(), name='create_label'),
    # /music/<label_id>/favorite_label
    url(r'^(?P<label_id>[0-9]+)/favorite_label/$', label.fav_label, name='fav_label'),
    # /music/filter/label/
    url(r'^filter/label', views.filter_label, name='filter_label'),

    # SEARCH ##
    # /music/search_results
    url(r'^search_results/$', views.searchresults, name='searchresults'),

    # USER AND AUTH ##
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    # url(r'^profile/$', views.update_profile, name='update_profile'),

    # MEDIA ##
    # url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT, }),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

audiad/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib import admin


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='home.html')),
    url(r'^music/', include('audiad.music.urls', namespace='music')),
    url(r'^admin/', include(admin.site.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

templates/base.html
<!DOCTYPE html>
<html lang="en">

    <!-- Head -->
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Audiad{% endblock %}</title>
        {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
        <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'themes/table/css/screen.css' %}" />
    </head>

    <!-- Body -->
    <body>
        <!-- Navigation -->
        <nav class="navbar navbar-inverse">

            <!-- Header Bar -->
            <div class="container-fluid">

                <!-- Index Link -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="nav navbar-brand" href="{% url 'music:index' %}">Audiad</a>
                </div>

                <!-- Menu Items -->
                <div class="collapse navbar-collapse" id="topNavBar">

                    <!-- Albums -->
                    <ul class="nav navbar-nav">
                        <li class="{% block albums_active %}{% endblock %}"><a href="{% url 'music:albums' 'all' %}"><span
                                class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums</a></li>
                    </ul>

                    <!-- Songs -->
                    <ul class="nav navbar-nav">
                        <li class="{% block songs_active %}{% endblock %}"><a href="{% url 'music:songs' 'all' %}"><span
                                class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Songs</a></li>
                    </ul>

                    <!-- Artists -->
                    <ul class="nav navbar-nav">
                        <li class="{% block artists_active %}{% endblock %}"><a href="{% url 'music:artists' 'all' %}"><span
                                class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Artists</a></li>
                    </ul>

                    <!-- Genres -->
{#                    <ul class="nav navbar-nav">#}
{#                        <li class="{% block genres_active %}{% endblock %}"><a href="{% url 'music:genres' 'all' %}"><span#}
{#                                class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Genres</a></li>#}
{#                    </ul>#}

                    <!-- Labels -->
{#                    <ul class="nav navbar-nav">#}
{#                        <li class="{% block labels_active %}{% endblock %}"><a href="{% url 'music:labels' 'all' %}"><span#}
{#                                class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Labels</a></li>#}
{#                    </ul>#}

                    <!-- Search -->
                    <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'music:searchresults' %}">
                        <div class="form-group">
                            <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                        </div>
                        <button type="submit" class="btn btn-default">Search</button>
                    </form>

                    <!-- Right Menu-->
                    <ul class="nav navbar-nav navbar-right">

{#                        <!-- Add Artist -->#}
{#                        <li>#}
{#                            <a href="{% url 'music:create_artist' %}">#}
{#                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Artist#}
{#                            </a>#}
{#                        </li>#}
{##}
{#                        <!-- Add Genre -->#}
{#                        <li>#}
{#                            <a href="{% url 'music:create_genre' %}">#}
{#                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Genre#}
{#                            </a>#}
{#                        </li>#}
{##}
{#                        <!-- Add Album -->#}
{#                        <li>#}
{#                            <a href="{% url 'music:create_album' %}">#}
{#                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album#}
{#                            </a>#}
{#                        </li>#}
                        <li>
                            <a href="{% url 'music:logout_user' %}">
                                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                            </a>
                        </li>
                    </ul>
                </div>

            </div>

        </nav>

        <!-- Dynamic Content -->
        {% block body %}
        {% endblock %}
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
        <script src="{% static 'js/main.js' %}"></script>
        {% comment %} ## Bootstrap 4.0 (unstable)
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
        {% endcomment %}
        <!-- Sentry JS SDK 2.1.+ required -->
        <script src="https://cdn.ravenjs.com/2.1.0/raven.min.js"></script>

        {% if request.sentry.id %}
          <script>
          Raven.showReportDialog({
            // grab the eventId generated by the Sentry SDK
            eventId: '{{ request.sentry.id }}',

            // use the public DSN (dont include your secret!)
            dsn: 'https://1c89626d8e02478e972af34e31360744@sentry.io/240094'
          });
          </script>


        <script>
        // configure the SDK as you normally would
        Raven.config('https://1c89626d8e02478e972af34e31360744@sentry.io/240094').install();

        /**
         * Report a routing error to Sentry and show a feedback dialog to
         * the user.
         *
         * > try {
         * >   renderRoute()
         * > } catch (err) {
         * >   handleRouteError(err);
         * > }
         */
        function handleRouteError(err) {
          Raven.captureException(err);
          Raven.showReportDialog();
        };
        </script>
        {% endif %}

    </body>


</html>

templates/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Music Manager {% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Music Manager</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'music:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'music:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/bootstrap-responsive.html
{% extends 'album/album_table.html' %}

{% block table-wrapper %}
<div class="table-container table-responsive">
    {% block table %}
    {{ block.super }}
    {% endblock table %}

    {% if table.page and table.paginator.num_pages > 1 %}
    {% block pagination %}
    {{ block.super }}
    {% endblock pagination %}
    {% endif %}
</div>
{% endblock table-wrapper %}

templates/fake-class-tables.html
{% extends "base/base.html" %}
{% load django_tables2 %}

{% block body %}
<h3>class based view via render_table</h3>
<pre>
{{ "{%" }} load django_tables2 {{ "%}" }}
{{ "{%" }} render_table example {{ "%}" }}
</pre>

{% render_table table %}

{% endblock %}

templates/home.html
{% extends "base_visitor.html" %}
{% block title %}Welcome to Audiad{% endblock %}
{% block body %}

    <!-- Dynamic Content -->
    <div class="albums-container container-fluid">
        <!-- Main Body -->
        <div class="row">
            <div class="col-sm-12 title text-center">

                {#todo change main page depending on login status#}
                <h1>Welcome to Audiad</h1>
                <br><br>
                <h2><a href="{% url 'music:register' %}">register</a></h2>
                <h2><a href="{% url 'music:login_user' %}">login</a></h2>

            </div>
        </div>
    </div>

{% endblock body %}

templates/index.html
{% extends 'base/base.html' %}
{% block title %}{{ album }}{% endblock %}
{% block index_active %}active{% endblock %}
{% block body %}

    <!-- Dynamic Content -->
    <div class="albums-container container-fluid">

        <!-- Main Body -->
        <div class="row">
            <div class="col-sm-12 title-brand">
                <h1>Music Manager</h1>
                <h2>Welcome {{ user.username.title }}</h2>
                <h5>You have {{ albums_count }} Albums</h5>
                <h5>You have {{ songs_count }} Songs</h5>
                <h5>You have {{ artists_count }} Artists</h5>
{#                <ul>#}
{#                    {% for url, text in urls %}#}
{#                        <li><a href="{{ url }}">{{ text }}</a></li>#}
{#                    {% endfor %}#}
{#                </ul>#}
                <li><a href="{% url 'music:index' %}">Here</a></li>
                <li><a href="{% url 'music:artists' 'all' %}">artists All</a></li>
                <li><a href="{% url 'music:artists' 'favorites' %}">artists Fav</a></li>
{#                <li><a href="{% url 'music:artists_list' %}">artists_list</a></li>#}
                <li><a href="{% url 'music:albums' 'all' %}">albums All</a></li>
                <li><a href="{% url 'music:albums' 'favorites' %}">albums Fav</a></li>
                <li><a href="{% url 'music:albums_list' %}">albums_list</a></li>
                <li><a href="{% url 'music:songs' 'all' %}">songs All</a></li>
                <li><a href="{% url 'music:songs' 'favorites' %}">songs Fav</a></li>
                <li><a href="{% url 'music:songs_list' %}">songs_list</a></li>
                <li><a href="{% url 'music:create_album'%}">Create Album</a></li>
                <li><a href="{% url 'music:searchresults'%}">searchresults</a></li>
                <li><a href="{% url 'music:create_artist'%}">create_artist</a></li>
                <li><a href="{% url 'music:create_genre'%}">create_genre</a></li>
                <li><a href="{% url 'music:search'%}">search</a></li>
                <li><a href="{% url 'music:register'%}">register</a></li>
                <li><a href="{% url 'music:login_user'%}">login_user</a></li>
                <li><a href="{% url 'music:logout_user'%}">logout_user</a></li>

            </div>
        </div>

        <!-- Fav Albums Panel -->
        <div class="row">
        <h2>Favourite Albums</h2>
            {% if user_albums %}

                <!-- Iterate Through Albums-->
                {% for album in user_albums %}

                    <!-- Panel -->
                    <div class="col-sm-4 col-lg-2">
                        <div class="thumbnail">

                            <!-- Album Image to go here -->
                            <a href="{% url 'music:album_detail' album.id %}"></a>

                            <!-- Main Caption -->
                            <div class="caption">

                                <!-- Albums Details -->
                                <h2>{{ album.title }}</h2>
                                <h4>{{ album.artist }}</h4>

                                <!-- View Details -->
                                <a href="{% url 'music:album_detail' album.id %}" class="btn btn-primary btn-sm"
                                   role="button">View
                                    Details</a>

                                <!-- Delete Album -->
                                <form action="{% url 'music:delete_album' album.id %}" method="post"
                                      style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="album_id" value="{{ album.id }}"/>
                                    <button type="submit" class="btn btn-default btn-sm">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </button>
                                </form>

                                <!-- Edit -->
                                <form action="{% url 'music:edit_album' album.id %}" method="post"
                                      style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="album_id" value="{{ album.id }}"/>
                                    <button type="submit" class="btn btn-default btn-sm"/>
                                    <span class="glyphicon glyphicon-edit"></span>
                                    </button>
                                </form>

                                <!-- Favorite Album -->
                                <a href="{% url 'music:fav_album' album.id %}"
                                   class="btn btn-default btn-sm btn-favorite"
                                   role="button">
                                    <span class="glyphicon glyphicon-star {% if album.fav %}active{% endif %}"></span>
                                </a>

                            </div>

                        </div>
                    </div>

                    <!-- ?? -->
                    {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}

                {% endfor %}

            {% else %}
                <p>There are no albums to show</p>

            {% endif %}
        </div>

        <!-- Fav Artists Panel -->
        <div class="row">
        <h2>Favourite Artists</h2>
            {% if user_artists%}

                <!-- Iterate Through Artist-->
                {% for artist in user_artists %}

                    <!-- Panel -->
                    <div class="col-sm-4 col-lg-2">
                        <div class="thumbnail">

                            <!-- Artist Image to go here -->
                            <a href="{% url 'music:artist_detail' artist.id %}"></a>

                            <!-- Main Caption -->
                            <div class="caption">

                                <!-- Artist Details -->
                                <h2>{{ artist.name }}</h2>
                                <h4>{{ artist.genre.all }}</h4>

                                <!-- View Details -->
                                <a href="{% url 'music:artist_detail' artist.id %}" class="btn btn-primary btn-sm"
                                   role="button">View
                                    Details</a>

                                <!-- Delete Artist -->
                                <form action="{% url 'music:delete_artist' artist.id %}" method="post"
                                      style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="artist_id" value="{{ artist.id }}"/>
                                    <button type="submit" class="btn btn-default btn-sm">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </button>
                                </form>

                                <!-- Edit Artist -->
                                <form action="{% url 'music:edit_artist' artist.id %}" method="post"
                                      style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="artist_id" value="{{ artist.id }}"/>
                                    <button type="submit" class="btn btn-default btn-sm"/>
                                    <span class="glyphicon glyphicon-edit"></span>
                                    </button>
                                </form>

                                <!-- Favorite Artist -->
                                <a href="{% url 'music:fav_artist' artist.id %}"
                                   class="btn btn-default btn-sm btn-favorite"
                                   role="button">
                                    <span class="glyphicon glyphicon-star {% if artist.fav %}active{% endif %}"></span>
                                </a>

                            </div>

                        </div>
                    </div>

                    <!-- ?? -->
                    {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}

                {% endfor %}

            {% else %}
                <p>There are no albums to show</p>

            {% endif %}
        </div>

        <!-- Fav Songs Panel -->
        <div class="row">
        <h2>Favourite Songs</h2>
            {% if user_songs %}

                <!-- Iterate Through Albums-->
                {% for song in user_songs %}

                    <!-- Panel -->
                    <div class="col-sm-4 col-lg-2">
                        <div class="thumbnail">

                            <!-- Songs Image to go here -->
                            <a href="{% url 'music:song_detail' song.id %}"></a>

                            <!-- Main Caption -->
                            <div class="caption">

                                <!-- Songs Details -->
                                <h2>{{ song.title }}</h2>
                                <h4>{{ song.artist }}</h4>

                                <!-- View Details -->
                                <a href="{% url 'music:song_detail' song.id %}" class="btn btn-primary btn-sm"
                                   role="button">View
                                    Details</a>

                                <!-- Delete Songs -->
                                <form action="{% url 'music:delete_song' song.id %}" method="post"
                                      style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="song_id" value="{{ song.id }}"/>
                                    <button type="submit" class="btn btn-default btn-sm">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </button>
                                </form>

                                <!-- Edit -->
                                <form action="{% url 'music:edit_song' song.id %}" method="post"
                                      style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="song_id" value="{{ song.id }}"/>
                                    <button type="submit" class="btn btn-default btn-sm"/>
                                    <span class="glyphicon glyphicon-edit"></span>
                                    </button>
                                </form>

                                <!-- Favorite Songs -->
                                <a href="{% url 'music:fav_song' song.id %}"
                                   class="btn btn-default btn-sm btn-favorite"
                                   role="button">
                                    <span class="glyphicon glyphicon-star {% if song.fav %}active{% endif %}"></span>
                                </a>

                            </div>

                        </div>
                    </div>

                    <!-- ?? -->
                    {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}

                {% endfor %}

            {% else %}
                <p>There are no albums to show</p>

            {% endif %}
        </div>


    </div>

{% endblock %}