audiad/music/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
import audiad.music.views.genre
from audiad.music.views.album import *
from audiad.music.views.song import *
from audiad.music.views.artist import *
from audiad.music.views.label import *
from audiad.music.views.genre import *
from audiad.music.views.views import IndexView
from audiad.music.views import views, song, album, artist, label, genre

app_name = 'music'

# todo Sort URL's to avoid unreachable links

urlpatterns = [

    # BASE PAGES ##
    # /music/
    url(r'^$', IndexView.as_view(), name='index'),

    # ALBUMS ##
    # /music/view/albums/<all:favourites>
    url(r'^view/albums/(?P<filter_by>[a-zA_Z]+)/$', Albums.as_view(), name='albums'),
    # /music/view/album/<album_id>
    url(r'^view/album/(?P<pk>\d+)/$', AlbumView.as_view(), name='album_form'),
    # /music/list/albums/<all:favourites>
    url(r'^list/albums/$', AlbumList.as_view(), name='albums_list'),
    # /music/table/albums/<all:favourites>
    url(r'^table/albums/$', AlbumTable.as_view(), name='albums_table'),
    # /music/detail/albums/<album_id>
    url(r'^detail/album/(?P<pk>\d+)$', AlbumDetailView.as_view(), name='album_detail'),
    # /music/edit/albums/<album_id>/
    url(r'^edit/album/(?P<pk>\d+)$', AlbumUpdate.as_view(), name='edit_album'),
    # /music/delete/albums/<album_id>
    url(r'^delete/album/(?P<pk>\d+)$', AlbumDelete.as_view(), name='delete_album'),
    # /music/create/album
    url(r'^create/album/$', AlbumCreate.as_view(), name='create_album'),
    # /music/favorite_album/<album_id>
    url(r'^favorite_album/(?P<album_id>[0-9]+)$', album.fav_album, name='fav_album'),
    # /music/filter/albums/
    url(r'^filter/albums$', views.filter_album, name='filter_album'),

    # SONGS ##
    # /music/songs/<all:favourites>
    url(r'^view/songs/(?P<filter_by>[a-zA_Z]+)/$', Songs.as_view(), name='songs'),
    # /music/list/song/
    url(r'^list/song/$', SongList.as_view(), name='song_list'),
    # /music/table/song/
    url(r'^table/song/$', SongTable.as_view(), name='song_table'),
    # /music/songs/<song_id>
    url(r'^detail/song/(?P<pk>\d+)$', SongDetailView.as_view(), name='song_detail'),
    # /music/songs/<song_id>/view
    url(r'^view/song/(?P<pk>\d+)/$', SongView.as_view(), name='song_form'),
    # /music/songs/<song_id>/edit/
    url(r'^edit/song/(?P<pk>\d+)$', SongUpdate.as_view(), name='edit_song'),
    # /music/songs/<song_id>/delete
    url(r'^delete/song/(?P<pk>\d+)$', SongDelete.as_view(), name='delete_song'),
    # /music/create/songs
    url(r'^create/song/$', SongCreate.as_view(), name='create_song'),
    # /music/<song_id>/favorite_song
    url(r'^(?P<song_id>[0-9]+)/favorite_song/$', song.fav_song, name='fav_song'),
    # /music/filter/songs/
    url(r'^filter/songs', views.filter_song, name='filter_songs'),

    # ARTISTS ##
    # /music/artist/<all:favourites>
    url(r'^view/artists/(?P<filter_by>[a-zA_Z]+)/$', Artists.as_view(), name='artists'),
    # /music/list/artist/
    url(r'^list/artists/$', ArtistList.as_view(), name='artists_list'),
    # /music/table/artist/
    url(r'^table/artists/$', ArtistTable.as_view(), name='artists_table'),
    # /music/artist/<artist_id>
    url(r'^detail/artist/(?P<pk>\d+)$', ArtistDetailView.as_view(), name='artist_detail'),
    # /music/artist/<artist_id>/view
    url(r'^view/artist/(?P<pk>\d+)/$', ArtistView.as_view(), name='artist_form'),
    # /music/artist/<artist_id>/edit/
    url(r'^edit/artist/(?P<pk>\d+)$', ArtistUpdate.as_view(), name='edit_artist'),
    # /music/artist/<artist_id>/delete
    url(r'^delete/artist/(?P<pk>\d+)$', ArtistDelete.as_view(), name='delete_artist'),
    # /music/create/artist
    url(r'^create/artist/$', ArtistCreate.as_view(), name='create_artist'),
    # /music/<artist_id>/favorite_artist
    url(r'^(?P<artist_id>[0-9]+)/favorite_artist/$', artist.fav_artist, name='fav_artist'),
    # /music/filter/artists/
    url(r'^filter/artists', views.filter_artist, name='filter_artist'),
    
    # GENRE ##
    # /music/genre/<all:favourites>
    url(r'^view/genres/(?P<filter_by>[a-zA_Z]+)/$', Genres.as_view(), name='genres'),
    # /music/list/genre/<all:favourites>
    url(r'^list/genres/$', GenreList.as_view(), name='genre_list'),
    # /music/table/genre/<all:favourites>
    url(r'^table/genres/$', GenreTable.as_view(), name='genre_table'),
    # /music/genre/<genre_id>
    url(r'^detail/genre/(?P<pk>\d+)$', GenreDetailView.as_view(), name='genre_detail'),
    # /music/genre/<genre_id>/view
    url(r'^view/genre/(?P<pk>\d+)/$', GenreView.as_view(), name='genre_form'),
    # /music/genre/<genre_id>/edit/
    url(r'^edit/genre/(?P<pk>\d+)$', GenreUpdate.as_view(), name='edit_genre'),
    # /music/genre/<genre_id>/delete
    url(r'^delete/genre/(?P<pk>\d+)$', GenreDelete.as_view(), name='delete_genre'),
    # /music/create/genre
    url(r'^create/genre/$', GenreCreate.as_view(), name='create_genre'),
    # /music/<genre_id>/favorite_genre
    url(r'^(?P<genre_id>[0-9]+)/favorite_genre/$', genre.fav_genre, name='fav_genre'),
    # /music/filter/genre/
    url(r'^filter/genre', views.filter_genre, name='filter_genre'),

    # LABEL ##
    # /music/label/<all:favourites>
    url(r'^view/labels/(?P<filter_by>[a-zA_Z]+)/$', Labels.as_view(), name='labels'),
    # /music/list/label/<all:favourites>
    url(r'^list/labels/$', LabelList.as_view(), name='label_list'),
    # /music/table/label/<all:favourites>
    url(r'^table/labels/$', LabelTable.as_view(), name='label_table'),
    # /music/label/<label_id>
    url(r'^detail/label/(?P<pk>\d+)$', LabelDetailView.as_view(), name='label_detail'),
    # /music/label/<label_id>/view
    url(r'^view/label/(?P<pk>\d+)/$', LabelView.as_view(), name='label_form'),
    # /music/label/<label_id>/edit/
    url(r'^edit/label/(?P<pk>\d+)$', LabelUpdate.as_view(), name='edit_label'),
    # /music/label/<label_id>/delete
    url(r'^delete/label/(?P<pk>\d+)$', LabelDelete.as_view(), name='delete_label'),
    # /music/create/label
    url(r'^create/label/$', LabelCreate.as_view(), name='create_label'),
    # /music/<label_id>/favorite_label
    url(r'^(?P<label_id>[0-9]+)/favorite_label/$', label.fav_label, name='fav_label'),
    # /music/filter/label/
    url(r'^filter/label', views.filter_label, name='filter_label'),

    # SEARCH ##
    # /music/search_results
    url(r'^search_results/$', views.searchresults, name='searchresults'),

    # USER AND AUTH ##
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    # url(r'^profile/$', views.update_profile, name='update_profile'),

    # MEDIA ##
    # url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT, }),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

audiad/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib import admin


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='home.html')),
    url(r'^music/', include('audiad.music.urls', namespace='music')),
    url(r'^admin/', include(admin.site.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

audiad/music/views/album.py
"""docstrings.


Example:


Attributes:
    module_level_variable1 (int): Module level variables may be documented in
        either the ``Attributes`` section of the module docstring, or in an
        inline docstring immediately following the variable.

Todo:

"""
# todo Finish docstring

from digg_paginator import DiggPaginator as Paginator
from django.core.paginator import PageNotAnInteger, EmptyPage
from django.core.urlresolvers import reverse_lazy
from django.db.models import Q, F
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, FormView, DetailView, UpdateView, DeleteView, CreateView, View
from django_tables2 import RequestConfig
from django_tables2.export import TableExport
from audiad.music.forms import AlbumForm
from audiad.music.models import Album, Artist, Song
from audiad.music.tables import AlbumTable as AT
from django.conf import settings
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.shortcuts import render
from django.views.decorators.cache import cache_page

CACHE_TTL = getattr(settings, 'CACHE_TTL', DEFAULT_TIMEOUT)


class Albums(View):
    """docstring

    Properties created with the ``@property`` decorator should be documented
    in the property's getter method.

    Attributes:
        attr1 (str): Description of `attr1`.
        attr2 (:obj:`int`, optional): Description of `attr2`.

    """
    # todo Finish docstring

    def get(self, request, filter_by='all'):
        """docstring

                Note:
                    Do not include the `self` parameter in the ``Args`` section.

                Args:
                    param1: The first parameter.
                    param2: The second parameter.

                Returns:
                    True if successful, False otherwise.

                """
        # todo Finish docstring
        if not request.user.is_authenticated():
            return render(request, 'music/auth/login.html')
        else:
            page = request.GET.get('page', 1)
            try:
                album_ids = []
                user_albums = []
                for album in Album.objects.filter(user=request.user):
                    album_ids.append(album.pk)
                    user_albums = Album.objects.filter(pk__in=album_ids)
                if user_albums:
                    if filter_by == 'favorites':
                        user_albums = user_albums.filter(fav=True)
            #     paginate_albums = Paginator(user_albums, 20, body=3, margin=1, tail=1)
            #     try:
            #         user_albums = paginate_albums.page(page)
            #     except PageNotAnInteger:
            #         user_albums = paginate_albums.page(1)
            #     except EmptyPage:
            #         user_albums = paginate_albums.page(paginate_albums.num_pages)
            except Album.DoesNotExist:
                user_albums = []
            return render(request, 'music/album/albums.html', {
                'album_list': user_albums,
                'filter_by': filter_by,
            })


class AlbumTable(ListView):
    """docstring

    Properties created with the ``@property`` decorator should be documented
    in the property's getter method.

    Attributes:
        attr1 (str): Description of `attr1`.
        attr2 (:obj:`int`, optional): Description of `attr2`.

    """
    # todo Finish docstring

    template_name = 'music/album/album_table.html'
    model = Album

    def get_context_data(self, **kwargs):
        """docstring

                Note:
                    Do not include the `self` parameter in the ``Args`` section.

                Args:
                    param1: The first parameter.
                    param2: The second parameter.

                Returns:
                    True if successful, False otherwise.

                """
        # todo Finish docstring
        if not self.request.user.is_authenticated():
            return render(self.request, 'music/auth/login.html')
        else:
            user = self.request.user
            context = super(AlbumTable, self).get_context_data(**kwargs)
            table = AT(Album.objects.all())
            table.paginate(page=self.request.GET.get('page', 1), per_page=25)
            RequestConfig(self.request).configure(table)
            export_format = self.request.GET.get('_export', None)
            if TableExport.is_valid_format(export_format):
                exporter = TableExport(export_format, table)
                return exporter.response('table.{}'.format(export_format))
            context['user'] = user
            context['table'] = table
            return context


class AlbumList(ListView):
    """docstring

    Properties created with the ``@property`` decorator should be documented
    in the property's getter method.

    Attributes:
        attr1 (str): Description of `attr1`.
        attr2 (:obj:`int`, optional): Description of `attr2`.

    """
    # todo Finish docstring

    def get(self, request, filter_by='all'):
        """docstring

                Note:
                    Do not include the `self` parameter in the ``Args`` section.

                Args:
                    param1: The first parameter.
                    param2: The second parameter.

                Returns:
                    True if successful, False otherwise.

                """
        # todo Finish docstring
        if not request.user.is_authenticated():
            return render(request, 'music/auth/login.html')
        else:
            page = request.GET.get('page', 1)
            try:
                album_ids = []
                albums = []
                for album in Album.objects.all():
                    album_ids.append(album.pk)
                    albums = Album.objects.filter(pk__in=album_ids)
                if filter_by == 'favorites':
                    albums = albums.filter(fav=True)
                paginate_albums = Paginator(albums, 20, body=3, margin=1, tail=1)
                try:
                    albums = paginate_albums.page(page)
                except PageNotAnInteger:
                    albums = paginate_albums.page(1)
                except EmptyPage:
                    albums = paginate_albums.page(paginate_albums.num_pages)
            except Album.DoesNotExist:
                albums = []
            return render(request, 'music/album/album_list.html', {
                'album_list': albums,
                'filter_by': filter_by,
            })


class AlbumDetailView(DetailView):
    """docstring

    Properties created with the ``@property`` decorator should be documented
    in the property's getter method.

    Attributes:
        attr1 (str): Description of `attr1`.
        attr2 (:obj:`int`, optional): Description of `attr2`.

    """
    # todo Finish docstring

    template_name = 'music/album/album_detail.html'
    model = Album

    def get_context_data(self, **kwargs):
        """docstring

                Note:
                    Do not include the `self` parameter in the ``Args`` section.

                Args:
                    param1: The first parameter.
                    param2: The second parameter.

                Returns:
                    True if successful, False otherwise.

                """
        # todo Finish docstring
        if not self.request.user.is_authenticated():
            return render(self.request, 'music/auth/login.html')
        else:
            user = self.request.user
            albums = Album.objects.all()
            artists = Artist.objects.all()
            songs = Song.objects.all()
            album = self.object
            context = super(AlbumDetailView, self).get_context_data(**kwargs)
            context['album'] = album
            context['user'] = user
            if self.object.genre.name:
                genre = self.object.genre.name
            context['similar_artist'] = artists.filter(Q(genre__name__icontains=genre)).distinct().exclude(name=album.artist)[:5]
            context['similar_album'] = albums.filter(Q(genre__name__icontains=genre)).distinct().exclude(title=album.title).filter(artist=F('artist')).distinct()[:5]
            context['similar_song'] = songs.filter(Q(genre__name__icontains=genre)).distinct().exclude(album=album.id)[:5]
            return context


class AlbumUpdate(UpdateView):
    """docstring

    Properties created with the ``@property`` decorator should be documented
    in the property's getter method.

    Attributes:
        attr1 (str): Description of `attr1`.
        attr2 (:obj:`int`, optional): Description of `attr2`.

    """
    # todo Finish docstring

    # todo Doesnt populate fields
    model = Album
    form_class = AlbumForm
    template_name = 'music/album/album_update.html'
    success_url = reverse_lazy('music:albums' 'all')

    def get_initial(self):
        initial = super(AlbumUpdate, self).get_initial()
        return initial


class AlbumView(FormView):
    """docstring

    Properties created with the ``@property`` decorator should be documented
    in the property's getter method.

    Attributes:
        attr1 (str): Description of `attr1`.
        attr2 (:obj:`int`, optional): Description of `attr2`.

    """
    # todo Finish docstring

    template_name = 'music/album/album_create.html'
    form_class = AlbumForm
    success_url = '/index/'

    # def form_valid(self, form):
    #     """docstring
    #
    #             Note:
    #                 Do not include the `self` parameter in the ``Args`` section.
    #
    #             Args:
    #                 param1: The first parameter.
    #                 param2: The second parameter.
    #
    #             Returns:
    #                 True if successful, False otherwise.
    #
    #             """
    #     # todo Finish docstring
    #     if not self.request.user.is_authenticated():

audiad/music/templates/music/search/album_search.html
{% extends 'base.html' %}

{% block content %}

<form type="get" action=".">
    <input type="text" name="q">
    <button type="submit">Search</button>
</form>

{% for album in albums %}
<h1>{{ album.title }}</h1>
<p>
    {{ album.artist }}
</p>
{% endfor %}
{% endblock %}

audiad/music/templates/music/search/search.html
{% extends 'base.html' %}

{% block content %}
    <h2>Search</h2>

    <form method="get" action=".">
        <table>
            {{ form.as_table }}
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" value="Search">
                </td>
            </tr>
        </table>

        {% if query %}
            <h3>Results</h3>

            {% for result in page.object_list %}
                <p>
                    <a href="{{ result.object.get_absolute_url }}">{{ result.object.title }}</a>
                </p>
            {% empty %}
                <p>No results found.</p>
            {% endfor %}

            {% if page.has_previous or page.has_next %}
                <div>
                    {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous{% if page.has_previous %}</a>{% endif %}
                    |
                    {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next &raquo;{% if page.has_next %}</a>{% endif %}
                </div>
            {% endif %}
        {% else %}
            {# Show some example queries to run, maybe query syntax, something else? #}
        {% endif %}
    </form>
{% endblock %}

audiad/music/templates/music/search/searchresults.html
{% extends 'base.html' %}
{% block title %}Search Results{% endblock %}
{% block body %}

    <!-- Dynamic Content -->
    <div class="container-fluid songs-container">

        <!-- Selection Header Panel -->
        <div class="row">
            <div class="col-sm-12">

                <!-- Selection Header -->
                <ul class="nav nav-pills" style="margin-bottom: 10px;">

                    <!-- Show All -->
                    <li role="presentation" {% if filter_by == 'all' %}class="active"{% endif %}><a
                            href="{% url 'music:songs' 'all' %}">View All</a></li>

                    <!-- Show Favourites -->
                    <li role="presentation" {% if filter_by == 'favorites' %}class="active"{% endif %}><a
                            href="{% url 'music:songs' 'favorites' %}">Favorites</a></li>

                </ul>

            </div>
        </div>

        <!-- Results Panel -->
        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-default">

                    <!-- Panel Body -->
                    <div class="panel-body">

                        <!-- Genre Table -->
                        <h3>Genre Results</h3>
                        <table class="table">

                            <!-- Table Head -->
                            <thead>
                            <tr>
                                <th>Genre</th>
                                <th>Favorite</th>
                            </tr>
                            </thead>

                            <!-- Table Body -->
                            <tbody>
                            {% for genre in genres %}
                                <tr>

                                    <!-- Genre -->
                                    <td>
                                        <a href="{% url 'music:genre_detail' genre.id %}" role="button">{{ genre.name }}</a>
                                    </td>

                                    <!-- Favorite -->
                                    <td>
                                        <a href="{% url 'music:fav_genre' genre.id %}" class="btn-favorite">
                                            <span class="glyphicon glyphicon-star {% if genre.fav %}active{% endif %}">
                                            </span>
                                        </a>
                                    </td>

                                </tr>
                            {% endfor %}
                            </tbody>

                        </table>

                        <!-- Label Table -->
                        <h3>Label Results</h3>
                        <table class="table">

                            <!-- Table Head -->
                            <thead>
                            <tr>
                                <th>Label</th>
                                <th>Favorite</th>
                            </tr>
                            </thead>

                            <!-- Table Body -->
                            <tbody>
                            {% for label in labels %}
                                <tr>

                                    <!-- Label -->
                                    <td>
                                        <a href="{% url 'music:label_detail' label.id %}" role="button">{{ label.name }}</a>
                                    </td>

                                    <!-- Favorite -->
                                    <td>
                                        <a href="{% url 'music:fav_label' label.id %}" class="btn-favorite">
                                            <span class="glyphicon glyphicon-star {% if label.fav %}active{% endif %}">
                                            </span>
                                        </a>
                                    </td>

                                </tr>
                            {% endfor %}
                            </tbody>

                        </table>

                        <!-- Song Table-->
                        <h3>Song Results</h3>
                        <table class="table">

                            <!-- Table Head -->
                            <thead>
                            <tr>
                                <th>Song Title</th>
                                <th>Artist</th>
                                <th>Playa</th>
                                <th>Album</th>
                                <th>Favorite</th>
                            </tr>
                            </thead>

                            <!-- Table Body -->
                            <tbody>
                            {% for song in songs %}
                                <tr>

                                    <!-- Song Title -->
                                    <td>
                                        <a href="{% url 'music:song_detail' song.id %}" role="button">{{ song.title }}</a>
                                    </td>

                                    <!-- Artist -->
                                    <td>
                                        <a href="{% url 'music:artist_detail' song.artist.id %}" role="button">{{ song.artist }}</a>
                                    </td>

                                    <!-- Playa -->
                                    <td>
                                        <a target="_blank" href="">
                                            <button type="button" class="btn btn-success btn-xs">
                                                <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                            </button>
                                        </a>
                                    </td>

                                    <!-- Album -->
                                    <td>
                                        <a href="{% url 'music:album_detail' song.album.id %}">{{ song.album.title }}</a>
                                    </td>

                                    <!-- Favorite -->
                                    <td>
                                        <a href="{% url 'music:fav_song' song.id %}" class="btn-favorite"><span
                                                class="glyphicon glyphicon-star {% if song.fav %}active{% endif %}"></span></a>
                                    </td>

                                </tr>
                            {% endfor %}
                            </tbody>

                        </table>

                        <!-- Artist Table -->
                        <h3>Artist Results</h3>
                        <table class="table">

                            <!-- Table Head -->
                            <thead>
                            <tr>
                                <th>Artist</th>
                                <th>Favorite</th>
                            </tr>
                            </thead>

                            <!-- Table Body -->
                            <tbody>
                            {% for artist in artists %}
                                <tr>

                                    <!-- Artist -->
                                    <td>
                                        <a href="{% url 'music:artist_detail' artist.id %}" role="button">{{ artist.name }}</a>
                                    </td>

                                    <!-- Favorite -->
                                    <td>
                                        <a href="{% url 'music:fav_artist' artist.id %}" class="btn-favorite">
                                            <span class="glyphicon glyphicon-star {% if artist.fav %}active{% endif %}">
                                            </span>
                                        </a>
                                    </td>

                                </tr>
                            {% endfor %}
                            </tbody>

                        </table>

                        <!-- Album Table -->
                        <h3>Album Results</h3>
                        <table class="table">

                            <!-- Table Head -->
                            <thead>
                            <tr>
                                <th>Album</th>
                                <th>Artist</th>
                                <th>Favorite</th>
                            </tr>
                            </thead>

                            <!-- Table Body -->
                            <tbody>
                            {% for album in albums %}
                                <tr>

                                    <!-- Album -->
                                    <td>
                                        <a href="{% url 'music:album_detail' album.id %}">{{ album.title }}</a>
                                    </td>

                                    <!-- Artist -->
                                    <td>
                                        <a href="{% url 'music:artist_detail' album.artist.id %}" role="button">{{ album.artist.name }}</a>
                                    </td>

                                    <!-- Favorite -->
                                    <td>
                                        <a href="{% url 'music:fav_album' album.id %}" class="btn-favorite">
                                            <span class="glyphicon glyphicon-star {% if album.fav %}active{% endif %}">
                                            </span>
                                        </a>
                                    </td>

                                </tr>
                            {% endfor %}
                            </tbody>

                        </table>

                    </div>

                </div>
            </div>
        </div>

    </div>

{% endblock %}